In [5]:
# CMIT 2024 Python Lecture 1 == CMIT_P1.ipynb  [jupyter nbconvert --to python notebook.ipynb]
# 11 June 2024 9am
''' Content in L1      [To launch juypter, type "python -m jupyter notebook"]
1) Basic commands for scalar numbers and texts
2) Programming basics:  
        (i) "if" coditional, (ii) "for" loop,  (iii) arrays, matrices, tensors
3) HW Exercise 1
'''
print('Hello CMIT participants :-)')
A = 2024.6

Hello CMIT participants :-)


In [11]:
print('Task 1 --- Basic commands for scalar numbers / print')
a = 2024  # 1) Basic commands for scalar numbers and texts ----------------------------------------
b = 6  # June
c = 2024.2 / 4
d = 2024 % 3  #Compute remainder
print('a b c =', a, b, c,  'd =',d,  '\n')

Task 1 --- Basic commands for scalar numbers / print
a b c = 2024 6 506.05 d = 2 



In [16]:
print('Task 2 --- Basic commands for processing/extracting texts')
F = 'CMIT_P1.ipynb' # This refers to the file that we are using   [STRING]
a = F[0:2];  b=F[1:4]    # Noting for ranges  0 start and  end-1   
What_is = F[-1]
print('\tStrings')
print('a =',a,  ' --> b =', b, '  Us =',F[0:4], ' ', 
      What_is, 'last two =', F[-2:])

Task 2 --- Basic commands for processing/extracting texts
	Strings
a = CM  --> b = MIT   Us = CMIT   b last two = nb


In [17]:
a = F.split('.')[0]
b = F.split('.')[1];   print(a, ' and ', b, ' or', F.split('.')[-1] )

CMIT_P1  and  ipynb  or ipynb


In [5]:
print( 'This is running: ', F.split('\\')[-1] )

This is running:  CMIT_P1.ipynb


In [18]:
print('Task 4 --- Basic commands for calling a math function')
import math

a = math.exp(1.0);  b=math.pi
print(a, b)

Task 4 --- Basic commands for calling a math function
2.718281828459045 3.141592653589793


2) Programming basics:           (i) "if" coditional,

In [22]:
print('\nTask 5 --- Programming basics:           (i) "if" coditional')
import numpy as np    # NB for "if"  (a) :   (b) tab 111111111111111111111111111111
import numpy
x = numpy.random.rand() - 0.5
y = np.random.rand() - 0.5
if x >= 0.0:
    print('non-negative x', x)
else:
    print('\tnegative x', x)

if y >= 0.1:
    print('positive y and y>=0.1', y)
else:
    print('\tless than 0.1', y)


Task 5 --- Programming basics:           (i) "if" coditional
non-negative x 0.3084322896635546
positive y and y>=0.1 0.3036613150737173


Task: How to compute the series $s1=\displaystyle\sum_{i=1}^n\sin(0.025 i\pi)$ and $s2=\displaystyle\sum_{j=0}^n \frac{x^j}{j!}$ 

In [23]:
print('\nTask 6 --- Programming basics:           (ii) "for" loop')

print('\tfor -- example 1')
n = 8;   s1 = 0    ## (ii) "for" loop
for i in range(1, n+1):
    s1 = s1 + math.sin(0.025*i*math.pi)   ##  or commonly    s1 += math.sin(0.025*i*math.pi)  
print('s1 =', s1, ' where n =',n)


Task 6 --- Programming basics:           (ii) "for" loop
	for -- example 1
s1 = 2.7243136681119875  where n = 8


In [24]:
print('\n\tfor -- example 2')

n = 3;   s2 = 0;  x=0.12
for j in range(n+1):
    t = x**j / math.factorial(j)
    print(j, t)
    s2 += t
print('When x=', x, ' s2 =', s2, ' Noting exp(x) =', math.exp(x) )


	for -- example 2
0 1.0
1 0.12
2 0.0072
3 0.00028799999999999995
When x= 0.12  s2 = 1.1274880000000003  Noting exp(x) = 1.1274968515793757


In [25]:
print('\n\tfor -- example 2 (efficient)')
s2 = 1;  x=0.12;  t=x;  n=25   # Efficient code // "if" for less printing
for j in range(1,n+1):
    if j % 5 == 0 or j==1:
        print(j, t)
    s2 += t
    t = x*t/(j+1)       # note when j=1,  t=x^2 / 2!
print('When x=', x, ',  s2 = %.8f' % s2, 'NB exp(x) = %.8f' % math.exp(x), ' er={:.2e}'.format(s2-math.exp(x)) )


	for -- example 2 (efficient)
1 0.12
5 2.0736e-07
10 1.7062765714285708e-16
15 1.1782001660054223e-26
20 1.5757971260505956e-37
25 6.1501466602268285e-49
When x= 0.12 ,  s2 = 1.12749685 NB exp(x) = 1.12749685  er=2.22e-16


(iii) arrays, matrices, tensors  // HOW TO use "apppend" to build up a LIST. 

In [27]:
print('\nTask 7 --- Programming basics:           (iii) arrays, matrices, tensors')
print('\n\t vectors a b c')
import numpy as np    # most common but there are other ways
a = np.arange(4)
b = np.arange(2,7)    # Moast identical to Matlab's linspace
print('a=',a, 'b=',b)
h = 0.125
c = np.arange(3.0, 4.0+h, h);  print(c)
print('Length: a b c =', len(a), len(b), len(c), ' and shape a =', a.shape)


Task 7 --- Programming basics:           (iii) arrays, matrices, tensors

	 vectors a b c
a= [0 1 2 3] b= [2 3 4 5 6]
[3.    3.125 3.25  3.375 3.5   3.625 3.75  3.875 4.   ]
Length: a b c = 4 5 9  and shape a = (4,)


Task :  generate a vector (array) v with $v_i=i\pi$ and a matrix A with $A_{i,j}=\sin( 0.25i + 0.32j ) +\delta_{i,j}$, where $i,j=0,...,4$ and $\delta_{i,i}=1$

In [28]:
print('\n\t vector v and matrix B   (by append)')
v = [];  B=[]
for i in range( 5 ):  # dim = 4
    x = i*math.pi;    v.append( x )
    B.append([])   # This is needed for notation [[]] for matrix
    for j in range( 5 ):
        y = math.sin( i*0.25 + j*0.32 );  
        if i==j:
            y=y+1
        B[i].append( y )
print('v =',np.array(v).astype(float), '\n')
print('B =', np.array(B))


	 vector v and matrix B   (by append)
v = [ 0.          3.14159265  6.28318531  9.42477796 12.56637061] 

B = [[1.         0.31456656 0.59719544 0.81919157 0.95801586]
 [0.24740396 1.53963205 0.77707175 0.935616   0.99916795]
 [0.47942554 0.73114583 1.9086335  0.99386836 0.97819661]
 [0.68163876 0.8772005  0.98370081 1.9903268  0.89640574]
 [0.84147098 0.9687151  0.99760638 0.92521152 1.75888071]]


In [29]:
# Matrix norm
from numpy import linalg as LA
B = np.array(B);   print('B shape (dim) =',B.shape)
B_n = LA.norm( B, ord='fro')
print('||B||_F = ', B_n)

print('\n\t Solution of a linear system Bx = b  (NB. matrix-vector product)')
b = np.array(v)
x =  LA.solve(B, b)  # Solve Bx = b
r = np.dot(B,x)-b
print('SOL x=',x)
print('Shapes =', B.shape,b.shape,x.shape)
print('Err =', r, ' Norm = %.3e' % LA.norm(r))

B shape (dim) = (5, 5)
||B||_F =  5.278611892966693

	 Solution of a linear system Bx = b  (NB. matrix-vector product)
SOL x= [-23.29452618 -13.11396172  -1.92270562   9.77875303  21.45820323]
Shapes = (5, 5) (5,) (5,)
Err = [ 4.40098768e-16 -1.33226763e-15  0.00000000e+00 -1.77635684e-15
 -5.32907052e-15]  Norm = 5.790e-15


In [14]:
print('\nTask 8 --- np.array to torch array (used a lot later in DL)')

# Tensors (Deep Learning use later)
import torch
A = np.zeros( (7,7,3) )
print(A.shape, 'typical color image (after imread and in plotting) numpy\n')

A1 = torch.from_numpy(A)
print(A1.size(), 'typical color image (torch tensor) same shape')

A2 = A1.permute([2,0,1])
print(A2.size(), 'typical color image (torch tensor) new shape towards DL')

A3 = A2[None,:]
print(A3.size(), 'typical color image (torch tensor) new shape ready for DL (with batch)\n')

print('\nTask 9 --- Form a typical torch array (batch,depth,dx,dy)')
A = np.zeros( (1,3,7,7) )
B = np.zeros( (4,3,7,7) )
print(np.shape(A), 'typical format for DL operations:    single batch data (3 channels)')
print(np.shape(B), 'typical format for DL operations:  when batch size = 4 (3 channels)')

A = torch.rand( 2, 3,7,7 )
print(A.shape, 'Torch rand more flexible for tensor shape (np cannot do > 2 dim)\n')

(7, 7, 3) typical color image (after imread and in plotting) numpy

torch.Size([7, 7, 3]) typical color image (torch tensor) same shape
torch.Size([3, 7, 7]) typical color image (torch tensor) new shape towards DL
torch.Size([1, 3, 7, 7]) typical color image (torch tensor) new shape ready for DL (with batch)

(1, 3, 7, 7) typical format for DL operations:    single batch data (3 channels)
(4, 3, 7, 7) typical format for DL operations:  when batch size = 4 (3 channels)
torch.Size([2, 3, 7, 7]) Torch rand more flexible for tensor shape (np cannot do > 2 dim)



Notation in HW 1 --- Below $H_{ij}=\frac{1}{(i+j-1)}$ for $i,j=1,...,n$.

In [30]:
# HOME WORK 1 -- If not sure about the maths concepts, check wiki or other sources
# 
print('\nHome work 1 --- Generate a matrix and compute its condition number\n')

s='TASK:  If not sure about the maths concepts, check wiki or other sources.\n\
   Write a code to generate the Hilbert matrix $H$ with $H_{ij}=1/(i_j-1)$ for $i,j=1,...,n$.\n\
   Then compute its condition number $cond(H)$ for $n=4, 8$ by numpy.linalg.cond\n\
   If your code runs okay,  just show it quickly and your answers on screen in the next lecture\n'
print(s)

import datetime
time0 = datetime.datetime.now().strftime("%Y %m %d @ %H:%M:%S"); print('\t time =', time0)
# NEXT Lecture CMIT 2
# Advanced programming:  "def" for a function, "class" for an advanecd function, plot/imshow
#   plus one or two examples 


Home work 1 --- Generate a matrix and compute its condition number

TASK:  If not sure about the maths concepts, check wiki or other sources.
   Write a code to generate the Hilbert matrix $H$ with $H_{ij}=1/(i_j-1)$ for $i,j=1,...,n$.
   Then compute its condition number $cond(H)$ for $n=4, 8$ by numpy.linalg.cond
   If your code runs okay,  just show it quickly and your answers on screen in the next lecture

	 time = 2024 06 10 @ 22:23:07


In [3]:
# NEXT Lecture CMIT 2
# Advanced programming:  "def" for a function, "class" for an advanecd function
#   plus one or two examples 